# Credit Risk Resampling Techniques

In [1]:
import warnings
warnings.filterwarnings('ignore')

In [2]:
import numpy as np
import pandas as pd
from pathlib import Path
from collections import Counter
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn import tree

# Read the CSV into DataFrame

In [3]:
# Load the data
file_path = Path('../Homework_Folder/lending_data.csv')
df = pd.read_csv(file_path)
df.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt loan_status  
0                5                 1       22800    low_risk  
1                3                 0       13600    low_risk  
2                3                 0       16100    low_risk  
3                5                 1       22700    low_risk  
4                5                 1       23000    low_risk

In [4]:
df_loans = pd.read_csv(file_path)
df_loans.head()
X = df_loans.copy()

# Split the Data into Training and Testing

In [5]:
# Define features
X.drop("derogatory_marks", axis=1, inplace=True)
X.head()

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672       own            52800        0.431818   
1     8400.0          6.692       own            43600        0.311927   
2     9000.0          6.963      rent            46100        0.349241   
3    10700.0          7.664       own            52700        0.430740   
4    10800.0          7.698  mortgage            53000        0.433962   

   num_of_accounts  total_debt loan_status  
0                5       22800    low_risk  
1                3       13600    low_risk  
2                3       16100    low_risk  
3                5       22700    low_risk  
4                5       23000    low_risk

In [6]:
# Create our features

X = df.drop(columns='loan_status')

# Create our target
y = df[['loan_status']]

In [7]:
X.describe()

loan_size  interest_rate  borrower_income  debt_to_income  \
count  77536.000000   77536.000000     77536.000000    77536.000000   
mean    9805.562577       7.292333     49221.949804        0.377318   
std     2093.223153       0.889495      8371.635077        0.081519   
min     5000.000000       5.250000     30000.000000        0.000000   
25%     8700.000000       6.825000     44800.000000        0.330357   
50%     9500.000000       7.172000     48100.000000        0.376299   
75%    10400.000000       7.528000     51400.000000        0.416342   
max    23800.000000      13.235000    105200.000000        0.714829   

       num_of_accounts  derogatory_marks    total_debt  
count     77536.000000      77536.000000  77536.000000  
mean          3.826610          0.392308  19221.949804  
std           1.904426          0.582086   8371.635077  
min           0.000000          0.000000      0.000000  
25%           3.000000          0.000000  14800.000000  
50%           4.000000          0.000000  18100.000000  
75%           4.000000          1.000000  21400.000000  
max          16.000000          3.000000  75200.000000

In [8]:
# Check the balance of our target values
y = df_loans["loan_status"]

In [9]:
# Create X_train, X_test, y_train, y_test
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1, stratify=y)

In [10]:
X_train

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
25729    10100.0          7.402  mortgage            50300        0.403579   
20176     9200.0          7.049  mortgage            46900        0.360341   
55080     8800.0          6.870  mortgage            45200        0.336283   
10410     8900.0          6.919  mortgage            45700        0.343545   
63110     8500.0          6.731       own            43900        0.316629   
...          ...            ...       ...              ...             ...   
4767     12300.0          8.346  mortgage            59100        0.492386   
26012     8300.0          6.634       own            43000        0.302326   
58637     6700.0          5.988  mortgage            36900        0.186992   
23339     9200.0          7.054  mortgage            47000        0.361702   
45677     7600.0          6.352  mortgage            40400        0.257426   

       num_of_accounts  derogatory_marks  total_debt  
25729                4                 1       20300  
20176                3                 0       16900  
55080                3                 0       15200  
10410                3                 0       15700  
63110                3                 0       13900  
...                ...               ...         ...  
4767                 6                 1       29100  
26012                2                 0       13000  
58637                1                 0        6900  
23339                3                 0       17000  
45677                2                 0       10400  

[58152 rows x 8 columns]

## Data Pre-Processing

Scale the training and testing data using the `StandardScaler` from `sklearn`. Remember that when scaling the data, you only scale the features data (`X_train` and `X_testing`).

In [11]:
# Create the StandardScaler instance
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder

In [12]:
le = LabelEncoder()

In [13]:
# Fitting and encoding the columns with the LabelEncoder

# RealEstate column
le.fit(df_loans["homeowner"])
df_loans["homeowner"] = le.transform(df_loans["homeowner"])

# Encoding RevLineCr column
le.fit(df_loans["loan_status"])
df_loans["loan_status"] = le.transform(df_loans["loan_status"])

df_loans.head()

loan_size  interest_rate  homeowner  borrower_income  debt_to_income  \
0    10700.0          7.672          1            52800        0.431818   
1     8400.0          6.692          1            43600        0.311927   
2     9000.0          6.963          2            46100        0.349241   
3    10700.0          7.664          1            52700        0.430740   
4    10800.0          7.698          0            53000        0.433962   

   num_of_accounts  derogatory_marks  total_debt  loan_status  
0                5                 1       22800            1  
1                3                 0       13600            1  
2                3                 0       16100            1  
3                5                 1       22700            1  
4                5                 1       23000            1

In [14]:
df_loans = pd.get_dummies(df_loans, columns=["homeowner", "loan_status"])
df_loans.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  homeowner_0  homeowner_1  homeowner_2  \
0                 1       22800            0            1            0   
1                 0       13600            0            1            0   
2                 0       16100            0            0            1   
3                 1       22700            0            1            0   
4                 1       23000            1            0            0   

   loan_status_0  loan_status_1  
0              0              1  
1              0              1  
2              0              1  
3              0              1  
4              0              1

In [15]:
# Save the file for forthcoming usage
file_path = Path("../Homework_Folder/lending_data_encoded.csv")
df_loans.to_csv(file_path, index=False)

In [16]:
# Loading data
file_path = Path("../Homework_Folder/lending_data_encoded.csv")
df_loans = pd.read_csv(file_path)
df_loans.head()

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  homeowner_0  homeowner_1  homeowner_2  \
0                 1       22800            0            1            0   
1                 0       13600            0            1            0   
2                 0       16100            0            0            1   
3                 1       22700            0            1            0   
4                 1       23000            1            0            0   

   loan_status_0  loan_status_1  
0              0              1  
1              0              1  
2              0              1  
3              0              1  
4              0              1

In [17]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
le.fit(df['homeowner'])
df['homeowner'] = le.transform(df['homeowner'])
le.fit(df['loan_status'])
df['loan_status'] = le.transform(df['loan_status'])

In [18]:
# Creating the scaler instance
data_scaler = StandardScaler()

In [19]:
# Fitting the scaler
data_scaler.fit(df_loans)

StandardScaler()

In [20]:
# Create the StandardScaler instance
scaler = StandardScaler()

In [21]:
df_loans_scaled = data_scaler.transform(df_loans)
pd.DataFrame(df_loans).head(5)

loan_size  interest_rate  borrower_income  debt_to_income  num_of_accounts  \
0    10700.0          7.672            52800        0.431818                5   
1     8400.0          6.692            43600        0.311927                3   
2     9000.0          6.963            46100        0.349241                3   
3    10700.0          7.664            52700        0.430740                5   
4    10800.0          7.698            53000        0.433962                5   

   derogatory_marks  total_debt  homeowner_0  homeowner_1  homeowner_2  \
0                 1       22800            0            1            0   
1                 0       13600            0            1            0   
2                 0       16100            0            0            1   
3                 1       22700            0            1            0   
4                 1       23000            1            0            0   

   loan_status_0  loan_status_1  
0              0              1  
1              0              1  
2              0              1  
3              0              1  
4              0              1

In [22]:
X_train

loan_size  interest_rate homeowner  borrower_income  debt_to_income  \
25729    10100.0          7.402  mortgage            50300        0.403579   
20176     9200.0          7.049  mortgage            46900        0.360341   
55080     8800.0          6.870  mortgage            45200        0.336283   
10410     8900.0          6.919  mortgage            45700        0.343545   
63110     8500.0          6.731       own            43900        0.316629   
...          ...            ...       ...              ...             ...   
4767     12300.0          8.346  mortgage            59100        0.492386   
26012     8300.0          6.634       own            43000        0.302326   
58637     6700.0          5.988  mortgage            36900        0.186992   
23339     9200.0          7.054  mortgage            47000        0.361702   
45677     7600.0          6.352  mortgage            40400        0.257426   

       num_of_accounts  derogatory_marks  total_debt  
25729                4                 1       20300  
20176                3                 0       16900  
55080                3                 0       15200  
10410                3                 0       15700  
63110                3                 0       13900  
...                ...               ...         ...  
4767                 6                 1       29100  
26012                2                 0       13000  
58637                1                 0        6900  
23339                3                 0       17000  
45677                2                 0       10400  

[58152 rows x 8 columns]

In [23]:
# Fit the Standard Scaler with the training data
X_scaler = scaler.fit(df_loans)

In [24]:
scaler.fit(df_loans)

StandardScaler()

In [25]:
# # Scale the training data
X_train_scaled = X_scaler.transform(df_loans)
X_test_scaled = X_scaler.transform(df_loans)

# Simple Logistic Regression

In [26]:
X = df[['loan_size', 'interest_rate', 'borrower_income', 'debt_to_income']]

In [27]:
y = df['loan_status']

In [28]:
x_cols = [i for i in df.columns if i not in ('ID', 'loan_status')]
X = df[x_cols]
y = df['loan_status']

In [29]:
# Normal train-test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [30]:
# Undersample the data using `RandomUnderSampler`
from imblearn.under_sampling import RandomUnderSampler
rus = RandomUnderSampler(random_state=1)
X_resampled, y_resampled = rus.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({0: 1881, 1: 1881})

In [31]:
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [32]:
classifier = LogisticRegression(random_state = 1)
classifier.fit(X_train, y_train)

LogisticRegression(random_state=1)

In [33]:
y_pred = classifier.predict(X_test)

In [34]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  563,    56],
       [  102, 18663]], dtype=int64)

In [35]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score
balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [36]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[  563,    56],
       [  102, 18663]], dtype=int64)

In [37]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.85      0.91      0.99      0.88      0.95      0.90       619
          1       1.00      0.99      0.91      1.00      0.95      0.91     18765

avg / total       0.99      0.99      0.91      0.99      0.95      0.91     19384



# Oversampling

In this section, you will compare two oversampling algorithms to determine which algorithm results in the best performance. You will oversample the data using the naive random oversampling algorithm and the SMOTE algorithm. For each algorithm, be sure to complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Print the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

### Naive Random Oversampling

In [38]:
%matplotlib inline
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.datasets import make_blobs
from collections import Counter

In [39]:
# Normal train-test split
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [40]:
# Resample the training data with the RandomOversampler
len(X_train)

# View the count of target classes with Counter
Counter(y_train)

Counter({1: 56271, 0: 1881})

In [41]:
# implement random oversampling
from imblearn.over_sampling import RandomOverSampler

In [42]:
# Train the Logistic Regression model using the resampled data
#initialize RandomOverSampler object
ros = RandomOverSampler(random_state=1)
X_resampled, y_resampled = ros.fit_resample(X_train, y_train)
Counter(y_resampled)

Counter({1: 56271, 0: 56271})

In [43]:
# Calculated the balanced accuracy score
from sklearn.metrics import balanced_accuracy_score

balanced_accuracy_score(y_test, y_pred)

0.9520479254722232

In [44]:
# Display the confusion matrix
from sklearn.metrics import confusion_matrix

y_pred = model.predict(X_test)
confusion_matrix(y_test, y_pred)

array([[  563,    56],
       [  102, 18663]], dtype=int64)

In [45]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.85      0.91      0.99      0.88      0.95      0.90       619
          1       1.00      0.99      0.91      1.00      0.95      0.91     18765

avg / total       0.99      0.99      0.91      0.99      0.95      0.91     19384



### SMOTE Oversampling

In [46]:
# Resample the training data with SMOTE
from imblearn.over_sampling import SMOTE

X_resampled, y_resampled = SMOTE(random_state=1, sampling_strategy=1.0).fit_resample(
    X_train, y_train
)
from collections import Counter

# View the count of target classes with Counter
Counter(y_resampled)
  

Counter({1: 56271, 0: 56271})

In [47]:
# Train the Logistic Regression model using the resampled data
model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [48]:
# Calculated the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [49]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  615,     4],
       [  116, 18649]], dtype=int64)

In [50]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.84      0.99      0.99      0.91      0.99      0.99       619
          1       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



In [51]:
# Undersampling

In [52]:
# Resample the data using the ClusterCentroids resampler
from imblearn.under_sampling import ClusterCentroids
cc = ClusterCentroids(random_state=1)
X_resampled, y_resampled = cc.fit_resample(X_train, y_train)

In [53]:
# View the count of target classes with Counter
Counter(y_resampled)

Counter({0: 1881, 1: 1881})

In [54]:
# Train the Logistic Regression model using the resampled data
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

In [55]:
# Calculate the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [56]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  615,     4],
       [  116, 18649]], dtype=int64)

In [57]:
# Print the imbalanced classification report
print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.84      0.99      0.99      0.91      0.99      0.99       619
          1       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



# Combination (Over and Under) Sampling

In this section, you will test a combination over- and under-sampling algorithm to determine if the algorithm results in the best performance compared to the other sampling algorithms above. You will resample the data using the SMOTEENN algorithm and complete the folliowing steps:

1. View the count of the target classes using `Counter` from the collections library. 
3. Use the resampled data to train a logistic regression model.
3. Calculate the balanced accuracy score from sklearn.metrics.
4. Display the confusion matrix from sklearn.metrics.
5. Generate a classication report using the `imbalanced_classification_report` from imbalanced-learn.

Note: Use a random state of 1 for each sampling algorithm to ensure consistency between tests

In [58]:
# Resample the training data with SMOTEENN
from imblearn.combine import SMOTEENN
sm = SMOTEENN(random_state=1)
X_resampled, y_resampled = sm.fit_resample(X_train, y_train)
Counter(y_resampled)

# View the count of target classes with Counter

Counter({0: 55609, 1: 55948})

In [66]:
# Train the Logistic Regression model using the resampled data
from sklearn.linear_model import LogisticRegression

model = LogisticRegression(solver='lbfgs', random_state=1)
model.fit(X_resampled, y_resampled)

LogisticRegression(random_state=1)

In [65]:
# Calculate the balanced accuracy score
y_pred = model.predict(X_test)
balanced_accuracy_score(y_test, y_pred)

0.9936781215845847

In [64]:
# Display the confusion matrix
confusion_matrix(y_test, y_pred)

array([[  615,     4],
       [  116, 18649]], dtype=int64)

In [63]:
# Print the imbalanced classification report
from imblearn.metrics import classification_report_imbalanced

print(classification_report_imbalanced(y_test, y_pred))

                   pre       rec       spe        f1       geo       iba       sup

          0       0.84      0.99      0.99      0.91      0.99      0.99       619
          1       1.00      0.99      0.99      1.00      0.99      0.99     18765

avg / total       0.99      0.99      0.99      0.99      0.99      0.99     19384



# Final Questions

1. Which model had the best balanced accuracy score?

   YOUR ANSWER HERE.

2. Which model had the best recall score?

    YOUR ANSWER HERE.

3. Which model had the best geometric mean score?

    YOUR ANSWER HERE.


In [ ]:
1. # The second model had the best balanced accuracy score.

2. # The second model had the best recall score.

3. # The first model had the best geometric mean score.